services:
    coldfusion:
        image: adobecoldfusion/coldfusion2021:2021.0.4
        ports:
        - "8500:8500"
        environment:
            - acceptEULA=YES
            - password=123
            - importCFSettings=mapping.json
            # if cfsetup export was created with a passphrase, you can provide it below
            #- importCFSettingsPassphrase=<yourpassphrase>
        volumes:
            - ./app:/app