services:
    coldfusion:
        image: adobecoldfusion/coldfusion2021:latest
        ports:
        - "8500:8500"
        environment:
            - acceptEULA=YES
            - password=123
            - setupScript=setupColdFusion.cfm
            - setupScriptDelete=false (default is that script IS deleted from /app folder after startup)
        volumes:
            - ./app:/app