services:
    coldfusion: 
        image: adobecoldfusion/coldfusion:latest
        ports:
        - "8500:8500"
        environment:
            - acceptEULA=YES
            - password=123
        volumes:
            - ./app:/app
