services:

    # Jaeger
    jaeger-all-in-one:
        image: jaegertracing/all-in-one:latest
        restart: always
        ports:
        - "16686:16686"
        - "14268"
        - "14250"

    # Zipkin
    zipkin-all-in-one:
        image: openzipkin/zipkin:latest
        environment:
        - JAVA_OPTS=-Xms1024m -Xmx1024m -XX:+ExitOnOutOfMemoryError
        restart: always
        ports:
        - "9411:9411"

    # Collector
    otel-collector:
        image: ${OTELCOL_IMG}
        restart: always
        command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
        volumes:
        - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
        ports:
        - "1888:1888"   # pprof extension
        - "8888:8888"   # Prometheus metrics exposed by the collector
        - "8889:8889"   # Prometheus exporter metrics
        - "13133:13133" # health_check extension
        - "4317:4317"   # OTLP gRPC receiver
        - "4318:4318"   # OTLP http receiver
        - "55679:55679" # zpages extension
        depends_on:
        - jaeger-all-in-one
        - zipkin-all-in-one
    
    prometheus:
        image: prom/prometheus:latest
        restart: always
        volumes:
        - ./prometheus.yaml:/etc/prometheus/prometheus.yml
        ports:
        - "9090:9090"
        
    coldfusion:
        build: . 
        ports:
        - "8500:8500"
        - "8088:8088"
        environment:
            - acceptEULA=YES
            - password=123
            - _JAVA_OPTIONS= -Dotel.javaagent.configuration-file=/opt/otelagent/config.properties -Dotel.javaagent.extensions=/opt/otelagent/cfmleditor-cfmlpage-instrumentation-1.0-all.jar -javaagent:"/opt/otelagent/opentelemetry-javaagent.jar"
        volumes:
            - ./app:/app