services:
    lucee: 
        build: . 
        volumes:
            - ./app:/var/www
        environment:
        - LUCEE_JAVA_OPTS=-javaagent:/opt/fusionreactor/fusionreactor.jar=name=lucee-fr,address=8088
        
        ports:
        - "8888:8888"
        - "8088:8088"
