apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    url: http://prometheus:9090 
    access: proxy
    editable: true
    isDefault: false

  - name: Jaeger
    type: jaeger
    url: http://jaeger-all-in-one:16686
    access: proxy
    editable: true
    isDefault: false